name: Django App Deploy

on:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  simple_build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: 3
      - name: Install docker-compose
        run: |
            pip install docker-compose
      - name: Use docker-compose to test
        run: |
            docker-compose run app sh -c "python manage.py test && flake8"
