name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install docker-compose via pip
    - run: pip install docker-compose
    - name: Build the Docker image using docker-compose
      run: docker-compose run app sh -c "python manage.py test && flake8"
